language: go

go_import_path: github.com/vancluever/terraform-provider-acme

go:
  - 1.10.x
  - 1.x

before_install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_26c593b079d9_key -iv $encrypted_26c593b079d9_iv -in .gitcookies.enc -out .gitcookies -d || true'

  # Download and install dep
  - curl -sI https://github.com/golang/dep/releases/latest | grep -Fi Location  | tr -d '\r' | sed "s/tag/download/g" | awk -F " " '{ print $2 "/dep-linux-amd64"}' | wget --output-document=$GOPATH/bin/dep -i -
  - chmod +x $GOPATH/bin/dep

  # Install linters and misspell
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - dep status -v
